### PR TITLE
Chapter 8 example

### PR DESCRIPTION
**Pull request by mars0i**
Hi,

I was interested in using Quil to create network graphics. After I bought Fry's Visualizing Data, I found your Quil translations of chapters 3-7 to be helpful--thanks.  I decided to try translating Fry's force layout code from Chapter 8. I got a minimal version working. Feel free to incorporate it into your repository if you'd like. All of my additions should be in the chapter8 directory, except that I updated some of the version numbers in project.clj.  (I created an earlier pull request, but then closed it because I realized I'd included some files that didn't belong there.)  There's a data directory under chapter 8 that includes the huckfinn data that Fry uses, but I never got around to using it.

I didn't try to match the stylistic decisions in your code. For example, I used Quil's functional mode.

I found it a bit difficult to make Fry's force layout code into a purely functional style, but eventually succeeded by taking liberties with the organization of the code. That is, it's more of a rewrite than a translation. (Nevertheless, I'd guess that a force layout algorithm implemented in Clojure from the start, by someone who understood how it works, would be simpler. Fry doesn't explain the principles captured in his force layout code, and I didn't do the research to fully understand force layout principles. I just tried to reproduce the same mathematical effects that I saw in Fry's code.)

### CODE REVIEW

**Comment by daveliepmann** [comment]
It looks like you removed `util.clj`, which is used by several other exercises (e.g. `hex-to-color` in figure 3-6). That's a breaking change.

The change to Clojure and Quil versions, though I understand it may be necessary or fun to use for Chapter 8, needs to be thoroughly tested to make sure nothing breaks in the earlier exercises. I'll try to make time for some testing on my side.

**Comment by mars0i** [comment]
Oh, my mistake about util.clj.  Sorry about that.  I hadn't worked on the Chapter 8 code for a while, and I had added a separate utility functions file (that I removed this morning), and I'd thought that util.clj was something that I had added at some point.  Didn't mean to remove your code!  

And I had assumed that the project.clj changes wouldn't matter, but you're right to be careful about that.  Why don't I make a new pull request with util.clj included, and with no changes to project.clj?

**Comment by daveliepmann** [comment]
No worries. The new pull request sounds like it would work for pre-chapter-8 exercises, but how would your exercises run? Would we have a note to comment out one version of Quil in order to run chapter 8?

**Comment by mars0i** [comment]
I'm pretty sure my code will run with the older versions, but I'll check.  I don't think I had a specific reason for the version changes.  I just figured I'd use the the latest versions.

**Comment by mars0i** [comment]
I was wrong.  Looks like my code does indeed depend on Clojure 1.6.0 and Quil 2.2.1.  The version of clj-time doesn't matter.  I'm not using that--not sure why I changed the version.

I'm not sure what to do.  I won't have time to work with vdquil in the near future.  No need for you to test all of your code with more recent versions of Clojure and Quil just because I contacted you.  There's no reason I can't just keep my chapter 8 code in my repo, and if and when you want to incorporate it, I'll be happy to do a pull request after merging in whatever changes you might have made.

**Comment by daveliepmann** [comment]
That sounds like a good plan. Thanks for your work--chapter 8 is pretty neat! :)

**Comment by mars0i** [comment]
Apologies for my ignorance.  Thanks for not just letting me mess things up!

**Pull request closed without merging**
